media: assets/img
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: about
    label: About
    type: file
    path: about.md
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: select
        options:
          values:
          - value: page
            label: page
      - name: body
        label: Body
        type: rich-text
  - name: links
    label: Links
    type: file
    path: links.md
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: select
        options:
          values:
          - value: page
            label: page
      - name: body
        label: Body
        type: rich-text
  - name: contact
    label: Contact
    type: file
    path: contact.md
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: select
        options:
          values:
          - value: page
            label: page
      - name: body
        label: Body
        type: rich-text
  - name: now
    label: Now
    type: file
    path: now.md
    view:
      fields: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: layout
        label: Layout
        type: select
        options:
          values:
          - value: page
            label: page
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Site configuration
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be used for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  - name: navigation
    label: Navigation
    type: file
    path: _data/navigation.yml
    fields:
      - name: main
        label: Main menu
        type: object
        list: true
        fields: 
          - { name: title, label: Title, type: string }
          - { name: url, label: URL, type: string }