title: Tom Donohue's Blog
author: Tom Donohue
email: monodot@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Tom's personal blog, sharing what I'm up to, opinions, and stuff I'm working on.

show_excerpts: false # set to true to show excerpts on the homepage

permalink: /:title/

twitter_username:   monodot
github_username:    monodot

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-clean-blog

paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
