### your site title here

title: Tom Donohue
url: https://monodot.co.uk
baseurl: ""

highlighter: rouge
markdown: kramdown

permalink: /:title/
### exclude the instructions / write-up in the README.md



# Tracker
analytics: UA-59556606-1

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md
- vendor/

disqus:
  shortname: monodot

plugins: [jekyll-seo-tag, jekyll-paginate, jekyll-sitemap, jekyll-last-modified-at]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      show_date: true
      show_cta_form: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      show_date: false
      show_cta_form: true

